Core.Permissions = {
	"ADMIN_ALL" : ["admin/all", "tenant/maintain"],
		"ROLE_MANAGE" : "role/manage",
    "EMPLOYEE_MANAGE" : "employee/all",
    "LEAVE_APPROVE" : "leave/approve",
    "TIME_APPROVE" : "time/approve",
    "TIME_MANAGE" : "time/manage",
    "EMPLOYEE_SS" : "ess/all",
    "PAYRULES_MANAGE" : "payrules/manage",
    "PAYROLL_MANAGE" : "payroll/manage",
		
		"RUN_PAYROLL_MANAGE" : "runpayroll/manage",
    "PAYROLL_ADDITIONAL_PAYMENTS_MANAGE" : "payroll_additional_payments/manage",
    "PAYROLL_RESULTS_VIEW" : "payroll_results/view",
    "PAYROLL_APPROVAL_CONFIG_MANAGE" : "payroll_approval_config/manage",
    "PAYROLL_APPROVAL_MANAGE" : "payroll_approval/manage",
		
		"LEAVE_MANAGE" : "leave/manage",
	  "PROCUREMENT_REQUISITION_APPROVE": "procurement_requisition/approve",
	  "TRAVEL_REQUISITION_APPROVE": "travel_requisition/approve",

	  "PROCUREMENT_REQUISITION_TREAT": "procurement_requisition/treat",
	  "TRAVEL_REQUISITION_TREAT": "travel_requisition/treat",

	  "PAYROLL_REPORTS_VIEW": "payroll_reports/view",
	  "AUDIT_REPORTS_VIEW": "audit_reports/view",
		"PROCUREMENT_REPORTS_VIEW": "procurement_reports/view",
	  "SUCCESSFACTORS_MANAGE": "successfactors/manage",
	  "SAP_HANA_MANAGE": "sap_hana/manage",

	//"CUSTOMERS_VIEW" : ["customers/view", "customers/maintain"],
	//"CUSTOMERS_MAINTAIN" : "customers/maintain",
	//"INVOICES_VIEW" : ["invoices/view", "invoices/manage"],
	//"INVOICES_MANAGE" : "invoices/manage",
	//"ORDERS_APPROVE" : "orders/approve",
	//"ORDERS_VIEW" : ["orders/view", "orders/manage"],
	//"ORDERS_MANAGE" : "orders/manage",
	//"ORDERTYPES_APPROVE" : "ordertypes/approve",
	//"PROMOTIONS_APPROVE" : "promotions/approve",
	//"PROMOTIONS_MANAGE" : "promotions/manage",
	//"PROMOTIONS_VIEW" : ["promotions/view", "promotions/manage"],
	//"REBATES_MANAGE" : "rebates/manage",
	//"REBATES_VIEW" : ["rebates/view", "rebates/manage"],
	//"RETURNORDERS_APPROVE" : "returnorders/approve",
	//"RETURNORDERS_VIEW" : ["returnorders/view", "returnorders/manage"],
	//"RETURNORDERS_MANAGE" : "returnorders/manage",
	"TENANT_MAINTAIN" : "tenant/maintain",
	"VIEW_ALL" : ["view/all", "admin/all", "tenant/maintain"]
};

Core.PermissionNames = {
	"admin/all" : "Administrator",
    "role/manage" : "Role Manage",
    "employee/all" : "Employee",
    "leave/manage" : "Manage Leave",
    "time/manage" : "Manage Time",
    "time/approve" : "Approve Time",
    "leave/approve" : "Approve Leave",
    "procurement_requisition/approve" : "Approve Procurement Requisition",
    "travel_requisition/approve" : "Approve Travel Requisition",

		"procurement_requisition/treat" : "Treat Procurement Requisition",
    "travel_requisition/treat" : "Treat Travel Requisition",

		"payrules/manage" : "Payrules Manage",

		"payroll/manage" : "Payroll Manage",
		"runpayroll/manage" : "Run Payroll Manage",
		"payroll_additional_payments/manage" : "Payroll Additional Payments Manage",
		"payroll_results/view" : "Payroll Results View",
		"payroll_approval_config/manage" : "Payroll Approval Config Manage",
		"payroll_approval/manage" : "Payroll Approval Manage",

		"payroll_reports/view" : "Payroll Reports View",
    "audit_reports/view" : "Audit Reports View",
    "procurement_reports/view" : "Procurement Reports View",
    "successfactors/manage" : "Successfactors Manage",
    "sap_hana/manage" : "Sap Hana Manage",

		"ess/all" : "Employee Self Service",
	//"customers/view" : "View Customers",
	//"customers/maintain" : "Maintain Customers",
	//"invoices/view" : "View Invoices",
	//"invoices/manage" : "Manage Invoices",
	//"orders/approve" : "Approve Orders",
	//"orders/view" : "View Orders",
	//"orders/manage" : "Manage Orders",
	//"ordertypes/approve" : "Approve Order Types",
	//"promotions/approve" : "Approve Promotions",
	//"promotions/manage" : "Manage Promotions",
	//"promotions/view" : "View Promotions",
	//"rebates/manage" : "Manage Rebates",
	//"rebates/view" : "View Rebates",
	//"returnorders/approve" : "Approve Return Orders",
	//"returnorders/view" : "View Return Orders",
	//"returnorders/manage" : "Manage Return Orders",
	"tenant/maintain" : "Maintain Tenant",
	"view/all" : "View All"
};
