############################################################
# Dockerfile to build the Meteor microservice container image
# Based on meteorhacks/meteord
############################################################

# Set the base image to MeteorD
FROM meteorhacks/meteord:devbuild

# File Author / Maintainer
MAINTAINER C2G Consulting

